version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
      day: monday
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
      - "automerge"
    groups:
      python-dev:
        patterns:
          - "pytest*"
          - "ruff"
          - "black"
          - "mypy"
          - "pre-commit"
          - "hypothesis"
      python-docs:
        patterns:
          - "mkdocs*"
          - "mkdocstrings*"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: monday
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
      - "automerge"
