coverage:
  status:
    project:
      default:
        target: auto
        threshold: 1%
    patch:
      default:
        target: 90%
        threshold: 2%

flags:
  python:
    paths:
      - python/src/
    carryforward: false
  julia:
    paths:
      - julia/src/
    carryforward: true
  rust:
    paths:
      - rust/src/
    carryforward: true
  cpp:
    paths:
      - cpp/include/
    carryforward: true

comment:
  layout: "reach,diff,flags,files"
  behavior: default
  require_changes: false
