using GIVPOptimizer
sphere(x) = sum(x .^ 2)
r = givp(sphere, [(-5.0, 5.0) for _ in 1:3]; seed=1)
println("meta keys: " * string(sort(collect(keys(r.meta)))))
println("meta hits: " * string(r.meta["hits"]))
opt = GIVPOptimizerWrapper(sphere, [(-5.0, 5.0) for _ in 1:3]; seed=2)
r2 = optimize!(opt)
println("wrapper best_fun: " * string(opt.best_fun))
println("history: " * string(length(opt.history)))
println("ALL OK")
