name: Julia CompatHelper

on:
  schedule:
    - cron: "0 0 * * 0" # Weekly on Sunday at midnight
  workflow_dispatch:

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

permissions: read-all

jobs:
  CompatHelper:
    runs-on: ubuntu-latest
    permissions:
      actions: read
      checks: read
      contents: write
      deployments: read
      issues: read
      packages: read
      pull-requests: write
      repository-projects: read
      security-events: read
      statuses: read
    steps:
      - uses: julia-actions/setup-julia@f6f565d9f7cf12f53dc8045742460d6260ad3b39 # v3.0.1
        with:
          version: "1.12"
      - uses: JuliaRegistries/CompatHelper.jl@5cf29123e1d355fcaa8420bb85014818fd06a84f # v3.13.1
        with:
          subdirs: julia
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          COMPATHELPER_PRIV: ${{ secrets.DOCUMENTER_KEY }}
