name: Fuzz

on:
    schedule:
        - cron: "0 4 * * 1" # every Monday at 04:00 UTC
    workflow_dispatch:

permissions: read-all

jobs:
    fuzzing:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
            - uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # v5
              with:
                  python-version: "3.12"
            - name: Install package and fuzzers
              run: |
                  pip install --require-hashes -r requirements/fuzz.txt
                  sh .github/scripts/install-package.sh
            - name: Run fuzz target with atheris (Linux CI run)
              run: |
                  python fuzz/fuzz_givp.py -atheris_runs=1000 -atheris_jobs=1
              continue-on-error: true
