name: Security Checks

on:
    push:
        branches: [ main ]
        paths:
            - "python/**"
            - "pyproject.toml"
            - ".github/workflows/security.yml"
    pull_request:
    schedule:
        - cron: "0 3 * * *"

permissions: read-all

jobs:
    pip-audit:
        name: pip-audit
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
            - uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
              with:
                  python-version: "3.12"
            - name: Install
              run: |
                  pip install --require-hashes -r python/requirements/audit.txt
                  sh .github/scripts/install-package.sh
            - name: Run pip-audit
              run: |
                  pip freeze --exclude-editable > /tmp/audit-reqs.txt
                  pip-audit -r /tmp/audit-reqs.txt

    bandit:
        name: Bandit scan
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
            - uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
              with:
                  python-version: "3.12"
            - name: Install Bandit
              run: pip install --require-hashes -r python/requirements/security.txt
            - name: Run Bandit
              run: bandit -r python/src -lll

    semgrep:
        name: Semgrep scan
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
            - name: Run Semgrep
              uses: semgrep/semgrep-action@713efdd345f3035192eaa63f56867b88e63e4e5d # v1
              with:
                  config: "p/ci"
